-- DEPRECATED: This schema is replaced by better-auth-schema.sql
-- 
-- Use better-auth-schema.sql instead - it includes:
-- 1. Complete Better Auth tables (user, session, account, verification)
-- 2. Updated cards table with TEXT user_id (Better Auth compatibility)  
-- 3. Proper foreign key relationships
-- 4. Performance indexes
-- 5. Updated_at triggers for all tables
--
-- To apply the complete schema:
-- 1. Go to Supabase SQL Editor
-- 2. Copy contents of better-auth-schema.sql
-- 3. Execute the SQL to create all tables
--
-- This will create a unified database with Better Auth + Interlink cards
-- all in the same Supabase PostgreSQL database.